//
//  ARScreenView.swift
//  AC_demo
//
//  Created by Mac on 01.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVI Xcode Templates so
//  you can apply MVI architecture to your iOS and Mac projects
//


import SwiftUI

struct ARScreenView: View {
    
    @ObservedObject var intent = ARScreenIntent()
    
    @State private var cameraState: ARCameraState = .normal
    
    var body: some View {
        ZStack {
            ARCameraView(arCameraState: $cameraState)
            
            VStack {
                Spacer()
                
                Button {
                    self.cameraState = .startAR
                } label: {
                    Text("Show AR")
                        .foregroundColor(.white)
                        .padding()
                        .background(Color.black)
                }
                .padding(.bottom, 20)
            }

        }
        .onAppear {
            self.intent.setup()
        }
    }
    
}

struct ARScreenView_Previews: PreviewProvider {
    static var previews: some View {
        ARScreenView()
    }
}
