//
//  ARScreenIntent.swift
//  AC_demo
//
//  Created by Mac on 01.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVI Xcode Templates so
//  you can apply MVI architecture to your iOS and Mac projects
//

import Combine
import SwiftUI

class ARScreenIntent: ObservableObject {
    
    let location = LocationManager.shared
    
    func setup() {
        location.startUpdating()
    }
    
}
